In [3]:
import keras
from keras.preprocessing.text import Tokenizer, text_to_word_sequence, one_hot
from keras.preprocessing.sequence import pad_sequences

In [4]:
text = ['this is a NLP starting day', 'today i will complete NLP basics', 'NLP has a very importatnt topic']

In [14]:
tk = Tokenizer()
tk.fit_on_texts(text)

In [15]:
seq = tk.texts_to_sequences(text)
seq

[[3, 4, 2, 1, 5, 6], [7, 8, 9, 10, 1, 11], [1, 12, 2, 13, 14, 15]]

In [17]:
mat = tk.sequences_to_matrix(seq)
mat

array([[0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.]])

In [21]:
import numpy as np
mat_tf = tk.sequences_to_matrix(seq, mode= 'tfidf')
np.round(mat_tf, 1)

array([[0. , 0.6, 0.7, 0.9, 0.9, 0.9, 0.9, 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. ],
       [0. , 0.6, 0. , 0. , 0. , 0. , 0. , 0.9, 0.9, 0.9, 0.9, 0.9, 0. ,
        0. , 0. , 0. ],
       [0. , 0.6, 0.7, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.9,
        0.9, 0.9, 0.9]])

In [23]:
tk.word_counts

OrderedDict([('this', 1),
             ('is', 1),
             ('a', 2),
             ('nlp', 3),
             ('starting', 1),
             ('day', 1),
             ('today', 1),
             ('i', 1),
             ('will', 1),
             ('complete', 1),
             ('basics', 1),
             ('has', 1),
             ('very', 1),
             ('importatnt', 1),
             ('topic', 1)])

In [25]:
tk.word_index

{'nlp': 1,
 'a': 2,
 'this': 3,
 'is': 4,
 'starting': 5,
 'day': 6,
 'today': 7,
 'i': 8,
 'will': 9,
 'complete': 10,
 'basics': 11,
 'has': 12,
 'very': 13,
 'importatnt': 14,
 'topic': 15}

In [28]:
tk.document_count

3

In [29]:
tk.word_docs

defaultdict(int,
            {'nlp': 3,
             'starting': 1,
             'this': 1,
             'is': 1,
             'day': 1,
             'a': 2,
             'basics': 1,
             'will': 1,
             'today': 1,
             'i': 1,
             'complete': 1,
             'has': 1,
             'importatnt': 1,
             'topic': 1,
             'very': 1})

In [31]:
pad_seq = pad_sequences(seq, padding = 'post')
pad_seq

array([[ 3,  4,  2,  1,  5,  6],
       [ 7,  8,  9, 10,  1, 11],
       [ 1, 12,  2, 13, 14, 15]], dtype=int32)